<a href="https://colab.research.google.com/github/maliboo-wow/ml-lab/blob/main/%D0%91%D1%96%D0%B1%D1%96_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

БУЛА НА ПАРІ

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [2]:
# Код студента
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [3]:
# Код студента
a = np.array([2, 4, 6, 8, 10])
print(a)
print(type(a))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [4]:
# Код студента
print(np.zeros(10))
print(np.ones(8))
print(np.full(6, 7))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [5]:
# Код студента
arr = np.arange(1, 21)
even_arr = np.arange(2, 21, 2)

print(arr)
print(even_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [6]:
# Код студента
print(np.linspace(0, 1, 11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [7]:
# Код студента
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [9]:
# Код студента
print("ndim:", matrix.ndim)
print("shape:", matrix.shape)
print("size:", matrix.size)
print("dtype:", matrix.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [11]:
# Код студента
arr = np.array([1.2, 3.5, 5.7, 7.9])
print(arr.astype(int))

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [14]:
# Код студента

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("Oстаннiй eлeмент:", arr[-1])
print("Елементи з індексами 2-5:", arr[2:6])
print("Koжeн дpугий елемент:", arr[::2])

Перший елемент: 10
Oстаннiй eлeмент: 80
Елементи з індексами 2-5: [30 40 50 60]
Koжeн дpугий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [17]:
# Код студента
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Елемент 7:", matrix[1, 2])
print("Другий рядок:", matrix[1])
print("Третій стовпець:", matrix[:, 2])
print("Підматриця:")
print(matrix[1:, :2])

Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця:
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [19]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [22]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("додавання:", a + b)
print("віднімання:", a - b)
print("множення:", a * b)
print("ділення:", a / b)

додавання: [11 22 33 44 55]
віднімання: [ -9 -18 -27 -36 -45]
множення: [ 10  40  90 160 250]
ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [24]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])

print("сума:", arr.sum())
print("середнє:", arr.mean())
print("мінімум:", arr.min())
print("максимум:", arr.max())
print("медіана:", np.median(arr))
print("std:", arr.std()) # standartne vydhylennya

сума: 108
середнє: 18.0
мінімум: 4
максимум: 42
медіана: 15.5
std: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [25]:
# Код студента
matrix = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("сума всіх:", matrix.sum())
print("по стовпцях:", matrix.sum(axis=0))
print("по рядках:", matrix.sum(axis=1))
print("середнє по стовпцях:", matrix.mean(axis=0))

сума всіх: 45
по стовпцях: [12 15 18]
по рядках: [ 6 15 24]
середнє по стовпцях: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [27]:
# Код студента
a = np.arange(1, 11)
print("квадрат кожного елемента:", a ** 2)
print("квадратний корінь кожного елемента:", np.sqrt(a))
print("натуральний логарифм кожного елемента:", np.log(a))

квадрат кожного елемента: [  1   4   9  16  25  36  49  64  81 100]
квадратний корінь кожного елемента: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
натуральний логарифм кожного елемента: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [29]:
# Код студента
a = np.array([3, 7, 12, 18, 21, 25, 30, 34])
print(a[a > 15])  #усі числа, більші за 15
print(a[a % 2 == 0])  #усі парні числа
print(a[(a >= 10) & (a <= 30)]) #числа в діапазоні від 10 до 30 включно

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [31]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [35]:
# Код студента
np.random.seed(42)

arr = np.random.randint(0, 101, size=20)

print(arr)
print("Кількість > 50:", np.sum(arr > 50))
print("Кількість <= 50:", np.sum(arr <= 50))

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість > 50: 12
Кількість <= 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [34]:
# Код студента
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
matrix_6x4 = arr.reshape(6, 4)
array_2x3x4 = arr.reshape(2, 3, 4)

print(matrix_4x6)
print("shape:", matrix_4x6.shape)

print(matrix_6x4)
print("shape:", matrix_6x4.shape)

print(array_2x3x4)
print("shape:", array_2x3x4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (6, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [36]:
# Код студента
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print("Вертикальне об'єднання:")
print(vertical)

print("Горизонтальне об'єднання:")
print(horizontal)

Вертикальне об'єднання:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтальне об'єднання:
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [38]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix.flatten())
print(matrix.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [39]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)
print(a - b)
print(a * 3)
print(b * 3)

[ 3  7 11]
[1 1 1]
[ 6 12 18]
[ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [37]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("np.dot():", np.dot(a, b))
print("Оператор @:", a @ b)

np.dot(): 32
Оператор @: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [40]:
# Код студента
v = np.array([3, 4])

norm = np.linalg.norm(v)
normalized_v = v / norm

print("Норма:", norm)
print("Нормалізований вектор:", normalized_v)

Норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [41]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)

print(cross_product)

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [42]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

cos = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle = np.degrees(np.arccos(cos))

print("косинус:", cos)
print("кут у градусах:", angle)

косинус: 0.7999999999999998
кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [46]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6]])

print("за допомогою .T :", A.T)
print("за допомогою np.transpose():", np.transpose(A))

за допомогою .T : [[1 4]
 [2 5]
 [3 6]]
за допомогою np.transpose(): [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [48]:
# Код студента
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(A * B)
print(A @ B)

[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]


A * B множить елементи на однакових позиціях (елемент на елемент), форма матриці зберігається.

A @ B - це матричний добуток за правилами лінійної алгебри: рядок першої матриці множиться на стовпець другої й сумується. Результат - зовсім інші числа.

### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [49]:
# Код студента
A = np.array([[4, 7], [2, 6]])

inv_A = np.linalg.inv(A)

print("визначник:", np.linalg.det(A))
print("обернена:\n", inv_A)
print("перевірка A @ inv:\n", (A @ inv_A).round(3))   # має бути одинична

визначник: 10.000000000000002
обернена:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
перевірка A @ inv:
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [50]:
# Код студента
A = np.array([[2, 1], [1, 3]])

b = np.array([5, 6])

print("Answer:", np.linalg.solve(A, b))

Answer: [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [52]:
# Код студента
I = np.eye(4)

A = np.arange(1, 17).reshape(4, 4)
result = A @ I

print("Одинична матриця:")
print(I)

print("Початкова матриця:")
print(A)

print("Результат множення:")
print(result)

print("Матриці однакові:", np.allclose(A, result))

Одинична матриця:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Початкова матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Результат множення:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
Матриці однакові: True


якщо помножити матрицю на одиничну, вона не змінюється - результат такий самий, як початкова матриця. np.allclose показав True, тобто вони однакові. Одинична матриця діє як число 1 у звичайному множенні.

## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [53]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])


print(A + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [54]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

v = np.array([10, 20, 30])

print(A + v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [55]:
# Код студента
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

mean = np.mean(A, axis=0)
std = np.std(A, axis=0)

print((A - mean) / std)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [56]:
# Код студента
np.random.seed(42)

random_ints = np.random.randint(1, 101, size=10)
random_matrix = np.random.random((3, 3))
normal_values = np.random.normal(size=1000)

print("Випадкові цілі числа:", random_ints)
print("Матриця 3x3:")
print(random_matrix)
print("Середнє нормального розподілу:", np.mean(normal_values))
print("Стандартне відхилення:", np.std(normal_values))

Випадкові цілі числа: [52 93 15 72 61 21 83 87 75 75]
Матриця 3x3:
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє нормального розподілу: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [62]:
# Код студента
np.random.seed(42)
grades = np.random.randint(0, 101, size=30)

print("Grades:", grades)
print("середня:", grades.mean())
print("медіана:", np.median(grades))
print("найвища:", grades.max())
print("найнижча:", grades.min())
print("не менше 60:", np.sum(grades >= 60))
print("% не менше 90:", np.mean(grades >= 90) * 100)

Grades: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
середня: 50.86666666666667
медіана: 54.5
найвища: 99
найнижча: 1
не менше 60: 13
% не менше 90: 6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [63]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])

print("по товарах:", sales.sum(axis=1))
print("по місяцях:", sales.sum(axis=0))
print("товар із max продажами (індекс):", sales.sum(axis=1).argmax())
print("місяць із max обсягом (індекс):", sales.sum(axis=0).argmax())
print("середнє по товарах:", sales.mean(axis=1))

по товарах: [600 380 820]
по місяцях: [400 420 480 500]
товар із max продажами (індекс): 2
місяць із max обсягом (індекс): 3
середнє по товарах: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [64]:
# Код студента
np.random.seed(0)
A = np.random.randint(1, 21, (5, 5))

print(A)
print("сума гол. діагоналі:", np.trace(A))
print("сума побічної:", np.trace(np.fliplr(A)))   #невпенена в цій строчці, підказав Джеміні
print("max кожного рядка:", A.max(axis=1))
print("min кожного стовпця:", A.min(axis=0))
B = A.copy()
B[B < A.mean()] = 0
print(B)

[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]
 [10 20 17 20  6]]
сума гол. діагоналі: 45
сума побічної: 53
max кожного рядка: [16 20 13 18 20]
min кожного стовпця: [ 7 10  1  4  4]
[[13 16  0  0  0]
 [ 0  0 20 19  0]
 [ 0 13  0  0  0]
 [15 18  0 14  0]
 [ 0 20 17 20  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [69]:
# Код студента
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])


print("1-2:", np.linalg.norm(X[0] - X[1]))
print("1-3:", np.linalg.norm(X[0] - X[2]))
print("2-3:", np.linalg.norm(X[1] - X[2]))

1-2: 1.7320508075688772
1-3: 5.196152422706632
2-3: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [68]:
# Код студента
np.random.seed(1)
A = np.random.randint(1, 10, (4, 4)).astype(float)

norms = np.linalg.norm(A, axis=1)  # норма кожного рядка
normalized = A / norms.reshape(4, 1) # ділимо кожен рядок на його норму

print("Початкова матриця:")
print(A)
print("Норми рядків:", norms)
print("Нормалізована матриця:")
print(normalized)

Початкова матриця:
[[6. 9. 6. 1.]
 [1. 2. 8. 7.]
 [3. 5. 6. 3.]
 [5. 3. 5. 8.]]
Норми рядків: [12.40967365 10.86278049  8.88819442 11.09053651]
Нормалізована матриця:
[[0.48349378 0.72524067 0.48349378 0.0805823 ]
 [0.09205746 0.18411492 0.73645969 0.64440223]
 [0.33752637 0.56254395 0.67505274 0.33752637]
 [0.45083482 0.27050089 0.45083482 0.72133571]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [70]:
# Код студента
A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])
b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)

print("розв'язок:", x)
print("перевірка A @ x:", (A @ x).round(3))
print("b:", b)

розв'язок: [ 2.22222222  3.44444444 -0.11111111]
перевірка A @ x: [9. 8. 3.]
b: [9 8 3]


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
